"""add billing table

Revision ID: 57382dd9ad53
Revises: 68504509edb2
Create Date: 2025-08-11 15:31:20.344402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57382dd9ad53'
down_revision: Union[str, Sequence[str], None] = '68504509edb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Ensure schema exists
    op.execute(sa.text('CREATE SCHEMA IF NOT EXISTS "porygon"'))
    # Create billing table only in this revision
    op.create_table('billing',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('context_name', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('tools', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tokens_input', sa.BigInteger(), nullable=False),
    sa.Column('tokens_output', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='porygon'
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users', schema='porygon')
    op.drop_table('summoners', schema='porygon')
    op.drop_table('messages', schema='porygon')
    op.drop_table('matches_tft', schema='porygon')
    op.drop_table('matches_lol', schema='porygon')
    op.drop_table('log_api', schema='porygon')
    op.drop_table('billing', schema='porygon')
    # ### end Alembic commands ###
