"""add discord user columns to billing and finalize pricing columns

Revision ID: 6d1eb3079273
Revises: 7f46981fa088
Create Date: 2025-08-11 16:00:31.427844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d1eb3079273'
down_revision: Union[str, Sequence[str], None] = '7f46981fa088'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add columns to existing billing table
    op.add_column('billing', sa.Column('discord_user_id', sa.String(length=64), nullable=True), schema='porygon')
    op.add_column('billing', sa.Column('discord_username', sa.String(length=128), nullable=True), schema='porygon')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users', schema='porygon')
    op.drop_table('summoners', schema='porygon')
    op.drop_table('model_pricing', schema='porygon')
    op.drop_table('messages', schema='porygon')
    op.drop_table('matches_tft', schema='porygon')
    op.drop_table('matches_lol', schema='porygon')
    op.drop_table('log_api', schema='porygon')
    op.drop_table('billing', schema='porygon')
    # ### end Alembic commands ###
