"""add model_pricing table

Revision ID: 7f46981fa088
Revises: 57382dd9ad53
Create Date: 2025-08-11 15:34:54.764119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f46981fa088'
down_revision: Union[str, Sequence[str], None] = '57382dd9ad53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Ensure schema exists
    op.execute(sa.text('CREATE SCHEMA IF NOT EXISTS "porygon"'))
    # Create only the model_pricing table in this revision
    op.create_table('model_pricing',
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usd_per_1k_tokens_input', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('usd_per_1k_tokens_output', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('model', 'period_start'),
    schema='porygon'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_pricing', schema='porygon')
    # ### end Alembic commands ###
